### PR TITLE
Added option to follow symlinks

### LINKED ISSUE #14: Symlinked directory doesn't sync
I've the following symlinked directory:

```
[munif:~/data/Drive] $ ls -l
lrwxrwxrwx 1 munif munif   33 Oct 26 14:03 documents -> /home/ubuntu/munif/data/documents
```

`/home/ubuntu/munif/data/documents` directory has many files and folders inside it.

I created  an empty folder named `documents` on my Google Drive.

When I run `drivesync`, nothing happens.

Dropbox's Linux client follows symlinks. It'd be nice to have this feature in DriveSync.

### PR DESCRIPTION
**Pull request by MunifTanjim**
resolves #14

### CODE REVIEW

**Comment by lewstherin** [comment]
+1

**Comment by MStadlmeier** [comment]
@MunifTanjim Thanks for the PR, looks good! Could you please rebase into the latest development commit and submit a pull request for the development branch instead?

**Comment by MunifTanjim** [comment]
@MStadlmeier how about now?

**Comment by MStadlmeier** [comment]
Thanks for your contribution! Sorry it took so long to get merged, GitHub is refusing to show me any type of notifications.

**Pull request merged**
